### ISSUE TITLE
Async validators

### ISSUE THREAD

**Issue by srph** [LevInteractive/react-serial-forms#10]
e.g., checking if username is unique, etc.

Is this possible atm?

**Comment by petesaia** [comment]
Currently async validation is not supported, but certainly an interesting idea. I will absolutely consider it, however, at the moment I'm not sure how it would work and am totally open to suggestions.

Perhaps one idea would be exposing a event dispatcher in the validation module. Something like this:

```javascript

validators.events.on('error', function(fields) {
  // Here you could call this.forceUpdate();
  // "fields" could also be available for extra information as to what the error is.
});
```

**Comment by petesaia** [comment]
Also, please note the recent update to custom validators here: https://github.com/LevInteractive/react-serial-forms/issues/10

**Comment by srph** [comment]
This is issue #10, I think you mistook it from #5?

We can check if the returned value is a `promise`.

```es6
validation.registerValidator({
  name: 'largerThanFive',
  invalid: function(value) {
    return checkUsernameIfValid(value)
      .then(({ data }) => data.error);
  },
  message: 'The field should be larger than 5.'
});
```

**Comment by petesaia** [comment]
Okay, I like it. I will work to get this fully implemented and tested this weekend.

**Comment by srph** [comment]
Woah thanks :heart: ! Buzz me up for anything, then.

**Comment by shankiesan** [comment]
This. Would. Be. Awesome.

If you need any help with user testing before pushing this, hit me up. I'm really keen for this feature for the same reason – async username checking.

**Comment by petesaia** [comment]
I'm sorry for the delay on this guys. The promise implementation is about 70% complete. Work has gotten really busy so I've had to put this to the side but will be back on it soon!

**Comment by petesaia** [comment]
It was a long time coming. Please check out v2.0. This was almost a complete re-write, but for the better. See the [updated docs here](https://github.com/LevInteractive/react-serial-forms#custom-validators).

Also please see the updated [demo which makes use of a async custom validator](http://levinteractive.github.io/react-serial-forms/examples/demo.html).

**Comment by srph** [comment]
Great, thanks. Sorry if I weren't able to help.

**Comment by petesaia** [comment]
Not a problem, @srph.
