### ISSUE TITLE
Migrate to React 0.14

### ISSUE THREAD

**Issue by petesaia** [LevInteractive/react-serial-forms#11]
Go: https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html

**Comment by shankiesan** [comment]
I assume that this is why I'm seeing `Warning: React.findDOMNode is deprecated. Please use ReactDOM.findDOMNode from require('react-dom') instead.` ... Correct?

**Comment by petesaia** [comment]
Correct.

**Comment by maikdiepenbroek** [comment]
This would be wel appreciated!

**Comment by maikdiepenbroek** [comment]
I've implemented it, see PR #13
