### ISSUE TITLE
How to make the inputs work with `react-bootstrap`

### ISSUE THREAD

**Issue by Industrial** [LevInteractive/react-serial-forms#14]
Hi.

I've read the documentation and tried the `BootstrapForm` example. It uses a `react-bootstrap` `ButtonInput` but I don't understand how to make all the other elements behave with this library. I have several other form elements that I would like to use like date/datetime inputs, selectbox with search/autocomplete. Can I get all these to work with this library?

gr,

Tom

**Comment by petesaia** [comment]
Yes, you can make just about anything work. I will be providing more examples of this. Components just need to extend `InputBase`. See how it's done [here](https://github.com/LevInteractive/react-serial-forms/blob/master/src/fields/InputField.js), [here](https://github.com/LevInteractive/react-serial-forms/blob/master/src/fields/SelectField.js), and [here](https://github.com/LevInteractive/react-serial-forms/blob/master/src/fields/TextareaField.js).
