### ISSUE TITLE
Radio serilization produces wrong values

### ISSUE THREAD

**Issue by motormuis** [LevInteractive/react-serial-forms#17]
Hi,

Thnx for your outstanding serilization/form solution. 
We have an issue with the serialization of radio buttons, there is no way currently to mark the selected radio button in the serialized data. I think the best solution would be to skip all radio values and only serialize the selected radio.

I made a PR for it (https://github.com/LevInteractive/react-serial-forms/pull/16). Can you please review/merge it?

**Comment by petesaia** [comment]
Sorry for the delay. Thanks for this, I've merged it. I will publish it to npm today or tomorrow with a few other fixes.
