### ISSUE TITLE
Is there a way to set error state programatically?

### ISSUE THREAD

**Issue by mnazim** [LevInteractive/react-serial-forms#18]
I need to set a field into error state based on the data I receive from API.
Is there a way I can do this?

May be something like,

    <InputField type="email" error={{message: "this email address is already been registered. Please choose a different one"}} />

**Comment by petesaia** [comment]
This is a good suggestion. I will work on getting it implemented in the next update. Thank you!

**Comment by petesaia** [comment]
This is now possible. Please check out v2.0. Also see the updated docs for an example. In your snippet, `message` would be the name of the validator - required, email, or some custom validator.
