### ISSUE TITLE
Unnecessary execution of form validation

### ISSUE THREAD

**Issue by Grygir** [LevInteractive/react-serial-forms#19]
Form validation action is triggered on any state change of page component, even if it is not related to a form (e.g. page header is changed -> validation errors are shown on form).

Page component state change invokes `updateComponent` method, and it leads to `componentWillReceiveProps` method execution for each form input and it calls `this.updateAttrs(nextProps);` all the time even if props really did not change.

**Comment by petesaia** [comment]
Thanks you!
