### ISSUE TITLE
how to assign custom message

### ISSUE THREAD

**Issue by deezahyn** [LevInteractive/react-serial-forms#2]
like 'first name is required'.  Also how to regenerate a form from a different schema?

**Comment by petesaia** [comment]
I've added customizable validation messages (and extendable validators) in v1.0.9. Please see the docs here: https://github.com/LevInteractive/react-serial-forms#custom-validation-messages

Could you provide a use case for this, please?

> Also how to regenerate a form from a different schema?

**Comment by petesaia** [comment]
Closing. Please open another issue if there is a feature request.
