### ISSUE TITLE
Can not update the static value from a higher component

### ISSUE THREAD

**Issue by emmarq** [LevInteractive/react-serial-forms#23]
Ok, thank you for your quick response. I personally prefer this project over redux-form. In my first use of react-serial-forms, i had a 'state' on a higher component who inject via props the initial data in a component with the form, and ocassionaly, reinitialize the initial state with ease. Now with the handy attrs method, that is not possible.

**Comment by petesaia** [comment]
Good catch, again. The fix has been pushed. I've also updated the [demo](http://levinteractive.github.io/react-serial-forms/examples/demo.html) to handle this scenario. See the _Favorite Food (fake ajax request)_ field. Let me know if you come across anything else and thanks for the support.
