### ISSUE TITLE
state[formName][inputName] destruction after state[formName] destruction

### ISSUE THREAD

**Issue by emmarq** [LevInteractive/react-serial-forms#24]
Good night. The fixes you have made are working nice. But now i came across with this issue. When a component containing a form fire the componentWillUnmout method, the state unregister the form and then try to unregister the inputs. this, of couse, give me a pretty: Cannot read property 'input_name' of undefined. And it makes sense. In some part of the code (i dont know where) its keeping the id of the form. If you need a replica, i could give it on sunday. But you have figured out well so far.

**Comment by petesaia** [comment]
Yes, a replica, or even better, a case in the unit tests would be really helpful. Much appreciated.

**Comment by tkandr** [comment]
Got the same issue.
http://screencloud.net/v/z0k8
'destroyForm' fires before 'destroyInput'. The problem appears when I click 'back' in the browser.

**Comment by tkandr** [comment]
Simple
`if (state[formName][inputName])` => `if (state[formName] && state[formName][inputName])`
Fixed this problem for me

**Comment by petesaia** [comment]
Thank you @tkandr! Merged and published. 2.0.4.
