### ISSUE TITLE
Warning: `value` prop on `input` should not be null

### ISSUE THREAD

**Issue by tkandr** [LevInteractive/react-serial-forms#26]
Just updated to react 15.0.1 and got this warning:

Warning: `value` prop on `input` should not be null. Consider using the empty string to clear the component or `undefined` for uncontrolled components.

https://github.com/facebook/react/pull/5048

**Comment by petesaia** [comment]
I was just about to add an issue for supporting 15.x. Looking in to it today.

**Comment by petesaia** [comment]
@tkandr Let me know how it works out for you.

**Comment by tkandr** [comment]
@petesaia Seems you forgot to update npm package :)

**Comment by petesaia** [comment]
Done!
