### ISSUE TITLE
Serialize radio does not seem to work

### ISSUE THREAD

**Issue by magsout** [LevInteractive/react-serial-forms#30]
At first, thanks for you awesome job. 

But when I tried your example, radio doesn't seems to work with serialize mehod. Even if I add some radio in my Component and I launch form.serialize() there is no value.

**Comment by petesaia** [comment]
Please post a snippet or example.

**Comment by petesaia** [comment]
Nevermind, was able to recreate. Push coming soon.

**Comment by magsout** [comment]
Thanks @petesaia . Any News about fix ?

**Comment by petesaia** [comment]
Sorry for the delay, I've been hit with some work that has taken priority. I should be able to finish this up tomorrow evening.

**Comment by magsout** [comment]
Don't worrie @petesaia takes your time. It's an open source project so thanks to take Time for this project ;)

**Comment by petesaia** [comment]
Please see #32. Sorry!
