### ISSUE TITLE
what is the correct behavior for multiple checkbox with the same name?

### ISSUE THREAD

**Issue by carlosrberto** [LevInteractive/react-serial-forms#4]
What is the correct behavior for multiple checkbox with the same name? 
should return only the checked elements, it is returning an array with all checked and not checked values.

**Comment by petesaia** [comment]
It sounds like you may want to do something like:

```
<InputField name='foo[]' type='checkbox' />
<InputField name='foo[]' type='checkbox' />
<InputField name='foo[]' type='checkbox' />
<InputField name='foo[]' type='checkbox' />
```

What sort of result were you looking for?

**Comment by carlosrberto** [comment]
Thank you @petesaia ! this will help me a lot and serve as a basis for other things.
