### ISSUE TITLE
BoostrapForm issues

### ISSUE THREAD

**Issue by daniel78uk** [LevInteractive/react-serial-forms#6]
While using the example reported on the docs about extending the Basic form I get the following this error:
Uncaught TypeError: Cannot read property 'createElement' of undefinedrender @ BoostrapForm.jsx:1ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext @ ReactCompositeComponent.js:790ReactCompositeComponentMixin._renderValidatedComponent @ ReactCompositeComponent.js:817ReactPerf.measure.wrapper @ ReactPerf.js:71

I'm using es6 with babelify,

```
import { React } from 'react';
import { BasicForm } from 'react-serial-forms';
import { Grid, Row, ButtonInput, Col } from 'react-bootstrap';

export default class BootstrapForm extends BasicForm {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <form onSubmit={this.props.onSubmit} method={this.props.method}>
        <Grid>
          {this.props.children}
          <Row>
            <Col xs={12}>
              <ButtonInput type='submit' bsStyle='primary' value={this.props.submitText} />
            </Col>
          </Row>
        </Grid>
      </form>
    );
  }
}
```

**Comment by daniel78uk** [comment]
actually i fixed this by changing this

```import { React } from 'react';```
to
```import React from 'react';```

The example in the docs is wrong

**Comment by petesaia** [comment]
Good catch, thanks!
