### ISSUE TITLE
how to regenerate a form from a different schema?

### ISSUE THREAD

**Issue by deezahyn** [LevInteractive/react-serial-forms#7]
> Could you provide a use case for this, please? It sounds like this is just a matter of re-rendering the component with different data.

Hi, thanks for the validation messages.  To answer your question: say I have a dropdown, and based from that dropdown I have different set of fields.  I just wanted to know how to regenerate the entire form, and set / clear data.  Is there an api to set the form data or do I have to manually set each field?

**Comment by petesaia** [comment]
Thanks for explaining. This would be a good demo, I think. The form doesn't have any method just for the purpose of re-rendering - only `validate()` and `serialize()`. It's truly "stateless". I would let React handle this by just updating the component's state or calling `forceUpdate()` explicitly.

Now for an (untested) example:

```javascript
export default class AdaptableForm extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      language: 'english'
    };
    this.onLanguageChange = this.onLanguageChange.bind(this);
  }
  fields() {
    if (this.state.language === 'portuguese') {
      return (
        <div class='pt'>
          <InputField name='title' placeholder='Name' />
          <InputField name='title' placeholder='Country' />
        </div>
      );
    }
    return (
      <div class='en'>
        <InputField name='title' placeholder='Nome' />
        <InputField name='title' placeholder='país' />
      </div>
    );
  }
  onLanguageChange() {
    const lang = event.target.value;
    this.setState({ // Will cause the form to rerender, thus updating the fields.
      language: lang
    });
  }
  render() {
    const languages: [
      { text: 'English', value: 'english' },
      { text: 'Portuguese', value: 'portuguese' }
    ]
    return (
      <BasicForm ref='myForm'>
        <SelectField
          name='language'
          value={this.state.language}
          options={languages}
          onChange={this.onLanguageChange}
        />
        {this.fields()}
      </BasicForm>
    );
  }
}
```

**Comment by deezahyn** [comment]
Thank you! I like you're approach of being stateless.  Say if the my form fields are coming from my api server.  Any hints in how to abstract that?

**Comment by petesaia** [comment]
I like to keep API requests in the action (if you're using a Flux approach). In the component, listen for updates, then `forceUpdate()`.
