### ISSUE TITLE
Validation fires on setState

### ISSUE THREAD

**Issue by shinta5150** [LevInteractive/react-serial-forms#8]
I make a call on componentWillMount to an ajax request. Then call SetState to populate a state variable. This seems to cause the validation to fire?

**Comment by petesaia** [comment]
Currently, yes. Validation happens per-field (blur or change) or when the parent re-renders with changed data. That said, I'm certainly open for an alternative flow of events.

**Comment by shinta5150** [comment]
Is it possible for on dirty as onmount should be initial state

**Comment by petesaia** [comment]
So in your case - if `componentWillMount` is loading an ajax request, it will certainly be different than the initial state once it has loaded, right?

**Comment by shinta5150** [comment]
It's loading initialisation properties that is used to initialize a component. 

Eg drop down values.

**Comment by petesaia** [comment]
After some time writing unit tests and thinking about different scenarios, I believe that the way it's working is the best solution. If you are loading things like remote options, you should halt (`return <span />`) the display of the field or form until it's ready. Currently, the initial properties the fields have on mount are the default and once changed or re-rendered will cause a validation. I'm still open to alternative ideas, I'll just need a detailed proposal.
