### ISSUE TITLE
debounce option on validation?

### ISSUE THREAD

**Issue by deezahyn** [LevInteractive/react-serial-forms#9]
say I want to delay the validation? Or is there a way to make this unobtrusive?  Validation only happens after the first click of submit.

**Comment by petesaia** [comment]
I believe the react way of doing it would be something like this:

```javascript
<Input validation={validate ? 'required' : null } />
```

Based on what `validate` is during `render()` would determine whether or not it should validate. Make sense?

**Comment by deezahyn** [comment]
@petesaia that's not debounce.  I'm talking about if the user type something, and say you add a debounce of 500ms, it will validate after 500ms.

**Comment by petesaia** [comment]
You're absolutely right. Please join in the discussion here about how best to accomplish async validators: https://github.com/LevInteractive/react-serial-forms/issues/10

Also see the latest update to the library: https://github.com/LevInteractive/react-serial-forms#custom-validators
